export ZSH=${HOME}/.oh-my-zsh
export PROJECT_HOME="$HOME/Projects"
export UPDATE_ZSH_DAYS=1
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
SPACESHIP_DOCKER_SHOW="false"
SPACESHIP_PYENV_PREFIX="➜"
SPACESHIP_PYENV_SYMBOL=" "
SPACESHIP_PYENV_SUFFIX=" "
SPACESHIP_PROMPT_ADD_NEWLINE="false"
SPACESHIP_PROMPT_SEPARATE_LINE="false"
SPACESHIP_NODE_SHOW="false"
SPACESHIP_DIR_TRUNC=1
SPACESHIP_PACKAGE_SHOW="false"
SPACESHIP_VENV_SHOW="false"

